import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

export default function RenderTest(props: {staticTime: string}) {
  const [dynamicTime, setDynamicTime] = useState<Date>(new Date())
  useEffect(() => {
    const interval = setInterval(() => {
      setDynamicTime(new Date())
    }, 1000)
    return () => clearInterval(interval)
  }, [])

  return (<>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <p>This was statically rendered at {`${props.staticTime}`}</p>
          <p>The client-side time is {`${dynamicTime.toISOString()}`}</p>
        </div>
      </main>

  </>)
}

export async function getStaticProps() {
  return {
    props: {
      staticTime: new Date().toISOString()
    }
  }
}